version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin#123
      MYSQL_DATABASE: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - emp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

volumes:
  mysql_data:
